name: Deploy demo site

on:
  push:
    branches:
      - main
    paths:
      - mkdocs_color_swatch_plugin
      - mkdocs.yml
      - docs/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.PYTHON_IMAGE }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pip install poetry==${{ vars.POETRY_VERSION }}

      - name: Install project dependencies
        run: poetry install

      - name: Deploy mkdocs to GitHub Pages
        run: poetry run mkdocs gh-deploy --force