name: Run pytest

on:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install Poetry
        run: pip install poetry==${{ vars.POETRY_VERSION }}

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest -v